[package]
name = "fritzbox-prometheus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fritzapi = "0.3.6"
metrics = "0.21.1"
metrics-exporter-prometheus = "0.12.1"
